---
# Install all the packages using apt

- name: Remove unneeded packages to speed up Ansible on Ubuntu
  apt: 
    name: "{{ item }}"
    state: absent 
    purge: yes
  with_items:
    - landscape-client
    - landscape-common
    - whoopsie
  when: ansible_distribution == 'Linux Mint'
  tags:
    - clean_package_mgmt

- name: Remove unattended upgrades packages to eliminate kernel conflicts and fill/space.
  apt: 
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - unattended-upgrades
  tags:
    - clean_package_mgmt

- name: Add extra repositories
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: present
    codename: "{{ codename }}"
  with_items:
    - ppa:peterlevi/ppa                                                                 # Variety repository
    - ppa:yg-jensge/shotwell                                                            # Shotwell repository
    - ppa:twodopeshaggy/jarun                                                           # Buku repository
    # - ppa:tomahawk/ppa                                                                # Tomahawk repository
    - deb http://repository.spotify.com stable non-free                                 # Spotify repository
    - ppa:otto-kesselgulasch/gimp                                                       # Gimp repository
    - ppa:tmate.io/archive                                                              # Tmate repository
    - deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ codename }} stable   # Docker repository
    - ppa:jonathonf/texlive                                                             # Texlive repository
    - ppa:nathan-renniewaldock/flux                                                     # F.lux repository
    - deb https://download.sublimetext.com/ apt/stable/					                # Sublimetext repository
    - ppa:ubuntu-mozilla-security/ppa                                                   # Firefox repository
    - deb https://dl.bintray.com/resin-io/debian stable etcher                          # Etcher repository
    # - remmina-ppa-team/remmina-next                                                     # FreeRDP repository
    - ppa:webupd8team/terminix                                                          # Tilix 
    - deb http://download.virtualbox.org/virtualbox/debian {{ codename }} contrib       # VirtualBox
  tags:
    - reposetup_package_mgmt

# - name: Add apt-keys 
#   become: yes
#   apt_key:
#     keyserver: hkp://keyserver.ubuntu.com:80 
#     id: "{{ item }}"
#     state: present
#   with_items:
#     - BBEBDCB318AD50EC6865090613B00F1FD2C19886		# Spotify key
#     - 0DF731E45CE24F27EEEB1450EFDC8610341D9410		# Spotify key
#     - 29A4B41A                                      # F.lux key
#     - 379CE192D401AB61                              # Etcher key
#   tags:
#     - reposetup_package_mgmt

- name: Add apt-keys by URL
  become: yes
  apt_key:
    url: "{{ item }}" 
    state: present
  with_items:
    - https://download.docker.com/linux/ubuntu/gpg              # Docker Key
    - https://download.sublimetext.com/sublimehq-pub.gpg        # Sublimetext Key
    - https://www.virtualbox.org/download/oracle_vbox_2016.asc  # VirtualBox Key
    - https://www.virtualbox.org/download/oracle_vbox.asc       # VirtualBox Key
  tags:
    - reposetup_package_mgmt

- name: Update system cache after added repositories
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when:
    - apt_update is not defined
  tags:
    - reposetup_package_mgmt

- name: Upgrade system after added repositories
  become: yes
  apt:
    upgrade: yes
  tags:
    - package_mgmt_reposetup

- name: Install common packages 
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - aptitude
    - build-essential
    - gcc 
    - python-dev
    - libffi-dev
    - libssl-dev
    - ubuntu-restricted-extras
    - firefox
    - dropbox
    - nemo-dropbox
    - sysstat
    - htop
    - nmap
    - zip
    - tcpdump
    - silversearcher-ag
    - autojump
    - curl
    - expect
    - tree
    - gzip
    - bzip2
    - zip
    - apt-transport-https
    - unzip
    - sshfs
    - whois
    - wireshark
    - tshark
    - ipcalc
    - wget
    - lftp
    - terminator
    - libxml2-utils
    - fping
    - vnstat
    - breeze-cursor-theme
    - zsh
    - ipcalc
    - apt-transport-https
    - ca-certificates
    - spotify-client
    - clementine
    - gimp
    - xsel
    #- texlive-full 
    - texmaker
    - software-properties-common
    - libapache2-mod-wsgi
    - variety
    - shotwell
    - buku
    - tomahawk
    - apache2
    - ntp 
    - fluxgui
#    - docbook-utils
    - docbook-xsl
    - docbook2odf
    - xsltproc
    - xmlto
    - libxml2-utils
    - fop
    - publican
    - openssl
    - libnss3-tools
    - openssh-client
    - gnupg
    - gnupg-agent
    - ssh-askpass
    - pwgen
    - git-core
    - git-flow
    - git-email
    - git-extras
    - ttf-liberation
    - ttf-mscorefonts-installer
    - easytag
    - vlc
    - k3b
    - k3b-i18n
    - man-db
    - screen
    - lzop
    - rsync
    - mlocate
    - iftop
    - iotop
    - dnsutils
    - ethtool
    - tcpdump
    - traceroute
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - docker-ce
    - sublime-text
    - linssid
    - ubuntu-restricted-addons
    - ubuntu-restricted-extras
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-plugins-ugly
    - gstreamer1.0-libav
    - aspell-es
    - calibre
    - laptop-mode-tools
    - etcher-electron
    - freerdp-x11
    - git-crypt
    - gnupg
    - pastebinit
    - byobu
    - byobu-extras
    - tmux
    - jq
    - pepperflashplugin-nonfree
    - redshift 
    - redshift-gtk
    - nethogs
    - shutter
    - gramps
    - font-manager
    - fonts-inconsolata
    - fonts-ubuntu-font-family-console
    - multitail
    - sqlitebrowser
    - tilix
    - virtualbox-5.2
    - dkms
  tags:
    - package_mgmt_apps

