---
# Install all the packages using apt

- name: Remove unneeded packages to speed up Ansible on Ubuntu
  apt: 
    name: "{{ item }}"
    state: absent 
    purge: yes
  with_items:
    - landscape-client
    - landscape-common
    - whoopsie
  when: ansible_distribution == 'Linux Mint'
  tags:
    - packages_init

- name: Remove unattended upgrades packages to eliminate kernel conflicts and fill/space.
  apt: 
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - unattended-upgrades
  tags:
    - packages_init

- name: Add extra repositories
  become: yes
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
    codename: "{{ codename }}"
  with_items:
    - "{{ var_repositories }}"
  tags:
    - packages_repos

# - name: Add apt-keys 
#   become: yes
#   apt_key:
#     keyserver: hkp://keyserver.ubuntu.com:80 
#     id: "{{ item }}"
#     state: present
#   with_items:
#     - BBEBDCB318AD50EC6865090613B00F1FD2C19886		# Spotify key
#     - 0DF731E45CE24F27EEEB1450EFDC8610341D9410		# Spotify key
#     - 29A4B41A                                      # F.lux key
#     - 379CE192D401AB61                              # Etcher key
#   tags:
#     - reposetup_package_mgmt

- name: Add apt-keys by URL
  become: true
  apt_key:
    url: "{{ item.key }}" 
    state: present
  with_items:
    - "{{ var_repokeys }}"
  tags:
    - packages_repos

- name: Update system cache after added repositories
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600
  when:
    - apt_update is not defined
  tags:
    - packages_repos

- name: Upgrade system after added repositories
  become: true
  apt:
    upgrade: true
  tags:
    - packages_repos

- name: Install packages 
  become: true
  apt:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - "{{ var_common_pkgs }}"
    - "{{ var_dev_pkgs }}"
    - "{{ var_tool_pkgs }}"
    - "{{ var_infra_pkgs }}"
    - "{{ var_themes_pkgs }}"
  tags:
    - packages_apt

