---

- name: Download additional deb packages
  get_url:
    url: "{{ item.url }}"
    dest: "{{ tmp_dir }}/packages/{{ item.name }}"
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items:
    - "{{ vars_extra_deb_packages }} "
  tags:
    - packages_extras

- name: Install additional deb packages
  become: yes
  apt:
    deb: "{{ tmp_dir}}/packages/{{ item.name }}"
    state: present
  with_items:
    - "{{ vars_extra_deb_packages }} "
  tags:
    - packages_extras

# - name: Download additional zip packages
#   get_url:
#     url: "{{ item.url }}"
#     dest: "{{ tmp_dir }}/packages/{{ item.name }}"
#     mode: u+rwx
#   with_items:
#     - "{{ vars_extra_zip_packages }}"
#   tags:
#     - packages_extras
#     - test

- name: Install additional zip packages
  become: true
  unarchive:
    src: "{{ item.url }}"
    dest: "{{ item.dest }}"
    keep_newer: true
    remote_src: true
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items:
    - "{{ vars_extra_zip_packages }}"
  tags:
    - packages_extras
    - test

- name: Download additional sh packages
  get_url:
    url: "{{ item.url }}"
    dest: "{{ tmp_dir }}/packages/{{ item.name }}"
    mode: u+rwx
  with_items:
    - "{{ vars_extra_sh_packages }}"
  tags:
    - packages_extras

- name: Install additional sh packages 
  become: yes
  raw: sh "{{ tmp_dir }}/packages/{{ item.name }}"
  ignore_errors: yes
  with_items:
    - "{{ vars_extra_sh_packages }}"
  tags:
    - packages_extras

