---

- name: Download additional deb packages
  get_url:
    url: "{{ item.url }}"
    dest: "{{ tmp_dir }}/packages/{{ item.name }}"
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items:
    - "{{ var_extra_deb_packages }} "
  tags:
    - packages_extras


- name: Install additional deb packages
  become: yes
  apt:
    deb: "{{ tmp_dir}}/packages/{{ item.name }}"
    state: present
  with_items:
    - "{{ var_extra_deb_packages }} "
  tags:
    - packages_extras

- name: Download additional sh packages
  get_url:
    url: "{{ item.url }}"
    dest: "{{ tmp_dir }}/packages/{{ item.name }}"
    mode: u+rwx
  with_items:
    - "{{ extra_sh_packages }}"
  tags:
    - packages_extras

- name: Install additional sh packages 
  become: yes
  raw: sh "{{ tmp_dir }}/packages/{{ item.name }}"
  ignore_errors: yes
  with_items:
    - "{{ extra_sh_packages }}"
  tags:
    - packages_extras

