--- 
# tasks file for 06-tunning 
 
- name: Copy Files with some kind of tunning 
  become: true 
  copy: 
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}" 
    owner: "{{ item.owner }}" 
    group: "{{ item.group }}" 
    mode: "{{ item.mode }}" 
  with_items: 
    - "{{ var_files_tunning }}" 
  tags: 
    - tunning 
 
- name: Setup AUTOSUSPEND_TIMEOUT variable  
  become: true 
  lineinfile: 
    path: /etc/laptop-mode/conf.d/runtime-pm.conf 
    regexp: '^AUTOSUSPEND_TIMEOUT=' 
    line: 'AUTOSUSPEND_TIMEOUT=-1' 
    state: present 
    owner: root 
    group: root 
    mode: 0644