---
# handlers file for 03-config-packages

- name: restart apache
  become: true
  service:
    name: apache2
    state: restarted

- name: restart docker
  become: true
  service:
    name: docker
    state: restarted