---
# tasks file for 04-vault

- name: Download dotfiles from own repository
  #become: yes
  git:
    repo: "git@github.com:k4ch0/dotfiles.git"
    dest: "/home/{{ user }}/.dotfiles"
    version: master
  tags:
    - vault

# - name: Delete any key
#   become: yes
#   file:
#     path: "/home/{{ user}}/.ssh/{{ item }}"
#     state: absent
#   with_items:
#     - github.com_rsa
#     - github.com_rsa.pub
#     - luiscachog.io_rsa
#     - luiscachog.io_rsa.pub
#   tags:
#     - vault

- name: Download vault files 
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "{{ item.perm }}"
  with_items:
    - "{{ vars_vault_files }}"
  tags:
    - vault

- name: Create symlink from vault folder
  become: yes
  file:
    src: "{{ item.src }}"
    path: "{{ item.dest }}"
    state: link
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644
  with_items:
    - "{{ vars_vault_symlinks }}"
  tags:
    - vault